<template>
  <el-card class="box-card-component" style="margin-left:0px;">
    <div class="box-card-header">
      平台公告
    </div>
    <div class="btn-box">
      <div v-for="(item,index) of btnTitles" :key="index" :class="[indexSelect == index ? 'btn-panel-select' : 'btn-panel-normal']" @click="changeTab(item)">
        {{ item }}
      </div>
    </div>
    <div style="margin-bottom: 8px;">
      <div v-for="(item,index) of noticeList" :key="index" class="card-right" style="color:gray;">
        <div class="list-left-box">
          <div class="list-left-title">【{{ item.type }}】</div>
          <div class="list-left-content">{{ item.title }}</div>
          <div v-if="!item.is_read" style="color: red; font-weight: bold; margin-left: 20px;font-size: 13px;">未读</div>
        </div>
        <div class="list-left-time">{{ item.create_time | parseTime('{y}-{m}-{d} {h}:{i}:{s}') }}</div>
      </div>
    </div>
    <div v-show="total>0" class="pagination-holder">
      <div class="pagination-total">共{{ total }}条</div>
      <pagination v-show="total>0" :total="total" :page.sync="listQuery.page" :limit.sync="listQuery.pageSize" @pagination="getList" />
    </div>
  </el-card>
</template>

<script>
import { mapGetters } from 'vuex'
import Pagination from '@/components/Pagination'
// import PanThumb from '@/components/PanThumb'
// import Mallki from '@/components/TextHoverEffect/Mallki'

export default {
  components: { Pagination },
  filters: {
    statusFilter(status) {
      const statusMap = {
        success: 'success',
        pending: 'danger'
      }
      return statusMap[status]
    }
  },
  data() {
    return {
      total: 0,
      listQuery: {
        page: 1,
        pageSize: 8
      },
      statisticsData: {
        article_count: 1024,
        pageviews_count: 1024
      },
      tableData: [
        {
          name: 'fruit-1',
          apple: 'apple-10',
          banana: 'banana-10',
          orange: 'orange-10'
        },
        {
          name: 'fruit-2',
          apple: 'apple-20',
          banana: 'banana-20',
          orange: 'orange-20'
        }
      ],
      key: 1, // table key
      formTheadOptions: ['apple', 'banana', 'orange'],
      btnTitles: ['公告', '未读公告'],
      indexSelect: 0,
      noticeList: [],
      notices: [
        {
          'id': 6698,
          'app_id': 0,
          'parent_id': 0,
          'post_type': 6,
          'inform_type': 1,
          'cost_integral': '0.00',
          'post_format': 1,
          'user_id': 135845,
          'post_status': 2,
          'comment_status': 1,
          'is_top': 2,
          'recommended': 1,
          'post_hits': 263,
          'post_like': 0,
          'comment_count': 0,
          'create_time': 1667618615,
          'update_time': 1667618615,
          'start_time': 1667618460,
          'end_time': 1675526400,
          'published_time': 1667618460,
          'delete_time': 0,
          'url': '',
          'post_title': '《萌仙记（九梦仙域）》上线通知',
          'post_author': '',
          'post_keywords': '',
          'post_excerpt': '',
          'post_source': '',
          'post_content': '\n<p style="text-align: center;">　　《萌仙记（九梦仙域）》上线通知</p>\n<p style="text-align: center;"><br></p>\n<p><br></p>\n<p><br></p>\n<p><br></p>\n<p>《萌仙记（九梦仙域）》，于2022年11月06号，上午10:00:00开启‘’动态开区’。</p>\n<p><br></p>\n<p><br></p>\n<p><br></p>\n<p><br></p>\n<p>《萌仙记（九梦仙域）》是一款以仙侠为题材，让你在修仙的世界里，享受非凡的热血战斗！更有霸气光武、酷炫时装、多种个性坐骑与你肩并肩战斗！聊天交友，寻找在仙侠道路的另一半，携手共进！热血激情的修仙之路就在你脚下，向前就可成就一段修仙传奇！众多系统、NPC交互任务、流畅的战斗体验，畅快不失游戏热趣！</p>\n<p><br></p>\n<p><br></p>\n<p><br></p>\n<p><br></p>\n<p>详细信息请登录app，搜索该款游戏查看。</p>\n',
          'post_content_filtered': null,
          'more': null,
          'agent_id': 1,
          'review_like': null,
          'review_hate': null,
          'title': '《萌仙记（九梦仙域）》上线通知',
          'excerpt': '',
          'game_id': 0,
          'pub_time': 1667618460,
          'type': '推广通知',
          'news_id': 6698,
          'game2': {
            'id': null,
            'name': null,
            'en_name': null,
            'en_abbr': null,
            'app_key': null,
            'tags': null,
            'category': null,
            'classify': null,
            'icon': null,
            'new_icon': null,
            'icon_share': null,
            'cp_payback_url': null,
            'cp_id': null,
            'parent_id': null,
            'package_name': null,
            'pay_switch': null,
            'logo_is_show': null,
            'float_is_show': null,
            'status': null,
            'is_delete': null,
            'delete_time': null,
            'is_online': null,
            'is_sdk': null,
            'is_bt': null,
            'is_auth': null,
            'list_order': null,
            'rise_order': null,
            'hot_order': null,
            'like_order': null,
            'fine_order': null,
            'publicity': null,
            'language': null,
            'description': null,
            'image': null,
            'run_time': null,
            'off_time': null,
            'create_time': null,
            'update_time': null,
            'promote_switch': null,
            'apple_id': null,
            'add_cp_time': null,
            'single_tag': null,
            'recycle_rate': null,
            'ext_info': null,
            'default_lang_code': null,
            'old_sign_key': null,
            'old_h5_game_id': null,
            'm3u8_url': null,
            'mp4_url': null,
            'mp4_type': null,
            'is_third': null,
            'selling_point': null,
            'gc_id': null,
            'real_name_tag': null,
            'real_name_bizid': null,
            'is_third_proper': null,
            'proper_game_id': null,
            'proper_agent_id': null,
            'is_box_proper': null,
            'add_status': null,
            'web_game_id': null
          },
          'img': '',
          'is_read': false
        },
        {
          'id': 6697,
          'app_id': 0,
          'parent_id': 0,
          'post_type': 6,
          'inform_type': 1,
          'cost_integral': '0.00',
          'post_format': 1,
          'user_id': 135845,
          'post_status': 2,
          'comment_status': 1,
          'is_top': 2,
          'recommended': 1,
          'post_hits': 223,
          'post_like': 0,
          'comment_count': 0,
          'create_time': 1667611894,
          'update_time': 1667611894,
          'start_time': 1667611740,
          'end_time': 1675526400,
          'published_time': 1667611740,
          'delete_time': 0,
          'url': '',
          'post_title': '《群英传奇-梦想三国（海蛇之战）》上线通知',
          'post_author': '',
          'post_keywords': '',
          'post_excerpt': '',
          'post_source': '',
          'post_content': '\n<p style="text-align: center;">　　《群英传奇-梦想三国（海蛇之战）》上线通知</p>\n<p style="text-align: center;"><br></p>\n<p style="text-align: center;"><br></p>\n<p><br></p>\n<p>《群英传奇-梦想三国（海蛇之战）》，于2022年11月06号，上午10:00:00开启‘’横扫千军’。</p>\n<p><br></p>\n<p><br></p>\n<p><br></p>\n<p>《群英传奇-梦想三国（海蛇之战）》是一款以传奇为题材的角色扮演类手机网络游戏。游戏有着丰富的任务及玩法，玩家之间即可协作互助，也可以相互竞争；强力的装备体系、唯美的钻石萌宠、炫酷的神兵神甲；攻占沙城赢奖励，一切都可以靠打BOSS产出，快来与兄弟共同征战！</p>\n<p><br></p>\n<p><br></p>\n<p><br></p>\n<p>详细信息请登录app，搜索该款游戏查看。</p>\n',
          'post_content_filtered': null,
          'more': null,
          'agent_id': 1,
          'review_like': null,
          'review_hate': null,
          'title': '《群英传奇-梦想三国（海蛇之战）》上线通知',
          'excerpt': '',
          'game_id': 0,
          'pub_time': 1667611740,
          'type': '推广通知',
          'news_id': 6697,
          'game2': {
            'id': null,
            'name': null,
            'en_name': null,
            'en_abbr': null,
            'app_key': null,
            'tags': null,
            'category': null,
            'classify': null,
            'icon': null,
            'new_icon': null,
            'icon_share': null,
            'cp_payback_url': null,
            'cp_id': null,
            'parent_id': null,
            'package_name': null,
            'pay_switch': null,
            'logo_is_show': null,
            'float_is_show': null,
            'status': null,
            'is_delete': null,
            'delete_time': null,
            'is_online': null,
            'is_sdk': null,
            'is_bt': null,
            'is_auth': null,
            'list_order': null,
            'rise_order': null,
            'hot_order': null,
            'like_order': null,
            'fine_order': null,
            'publicity': null,
            'language': null,
            'description': null,
            'image': null,
            'run_time': null,
            'off_time': null,
            'create_time': null,
            'update_time': null,
            'promote_switch': null,
            'apple_id': null,
            'add_cp_time': null,
            'single_tag': null,
            'recycle_rate': null,
            'ext_info': null,
            'default_lang_code': null,
            'old_sign_key': null,
            'old_h5_game_id': null,
            'm3u8_url': null,
            'mp4_url': null,
            'mp4_type': null,
            'is_third': null,
            'selling_point': null,
            'gc_id': null,
            'real_name_tag': null,
            'real_name_bizid': null,
            'is_third_proper': null,
            'proper_game_id': null,
            'proper_agent_id': null,
            'is_box_proper': null,
            'add_status': null,
            'web_game_id': null
          },
          'img': '',
          'is_read': false
        },
        {
          'id': 6690,
          'app_id': 0,
          'parent_id': 0,
          'post_type': 6,
          'inform_type': 1,
          'cost_integral': '0.00',
          'post_format': 1,
          'user_id': 135845,
          'post_status': 2,
          'comment_status': 1,
          'is_top': 2,
          'recommended': 1,
          'post_hits': 293,
          'post_like': 0,
          'comment_count': 0,
          'create_time': 1667560691,
          'update_time': 1667560691,
          'start_time': 1667560560,
          'end_time': 1675440000,
          'published_time': 1667560560,
          'delete_time': 0,
          'url': '',
          'post_title': '《龙神大陆（送月卡直升）》上线通知',
          'post_author': '',
          'post_keywords': '',
          'post_excerpt': '',
          'post_source': '',
          'post_content': '\n<p style="text-align: center;">　　《龙神大陆（送月卡直升）》上线通知</p>\n<p style="text-align: center;"><br></p>\n<p style="text-align: center;"><br></p>\n<p><br></p>\n<p><br></p>\n<p>《龙神大陆（送月卡直升）》，于2022年11月07号，上午9:00:00开启‘’福利1区’。</p>\n<p><br></p>\n<p><br></p>\n<p><br></p>\n<p><br></p>\n<p>《龙神大陆（送月卡直升）》是一款Q版日韩风魔幻动作手游。游戏打造梦幻冒险世界，多个角色任你选择，丰富伙伴阵容轻松召集，培养你的冒险队伍，闯荡各个副本，开启你的冒险旅程。</p>\n<p><br></p>\n<p><br></p>\n<p><br></p>\n<p><br></p>\n<p>详细信息请登录app，搜索该款游戏查看。</p>\n',
          'post_content_filtered': null,
          'more': null,
          'agent_id': 1,
          'review_like': null,
          'review_hate': null,
          'title': '《龙神大陆（送月卡直升）》上线通知',
          'excerpt': '',
          'game_id': 0,
          'pub_time': 1667560560,
          'type': '推广通知',
          'news_id': 6690,
          'game2': {
            'id': null,
            'name': null,
            'en_name': null,
            'en_abbr': null,
            'app_key': null,
            'tags': null,
            'category': null,
            'classify': null,
            'icon': null,
            'new_icon': null,
            'icon_share': null,
            'cp_payback_url': null,
            'cp_id': null,
            'parent_id': null,
            'package_name': null,
            'pay_switch': null,
            'logo_is_show': null,
            'float_is_show': null,
            'status': null,
            'is_delete': null,
            'delete_time': null,
            'is_online': null,
            'is_sdk': null,
            'is_bt': null,
            'is_auth': null,
            'list_order': null,
            'rise_order': null,
            'hot_order': null,
            'like_order': null,
            'fine_order': null,
            'publicity': null,
            'language': null,
            'description': null,
            'image': null,
            'run_time': null,
            'off_time': null,
            'create_time': null,
            'update_time': null,
            'promote_switch': null,
            'apple_id': null,
            'add_cp_time': null,
            'single_tag': null,
            'recycle_rate': null,
            'ext_info': null,
            'default_lang_code': null,
            'old_sign_key': null,
            'old_h5_game_id': null,
            'm3u8_url': null,
            'mp4_url': null,
            'mp4_type': null,
            'is_third': null,
            'selling_point': null,
            'gc_id': null,
            'real_name_tag': null,
            'real_name_bizid': null,
            'is_third_proper': null,
            'proper_game_id': null,
            'proper_agent_id': null,
            'is_box_proper': null,
            'add_status': null,
            'web_game_id': null
          },
          'img': '',
          'is_read': false
        },
        {
          'id': 6687,
          'app_id': 0,
          'parent_id': 0,
          'post_type': 6,
          'inform_type': 1,
          'cost_integral': '0.00',
          'post_format': 1,
          'user_id': 135845,
          'post_status': 2,
          'comment_status': 1,
          'is_top': 2,
          'recommended': 1,
          'post_hits': 258,
          'post_like': 0,
          'comment_count': 0,
          'create_time': 1667550442,
          'update_time': 1667550442,
          'start_time': 1667550300,
          'end_time': 1675440000,
          'published_time': 1667550300,
          'delete_time': 0,
          'url': '',
          'post_title': '《明日大亨（专服）》上线通知',
          'post_author': '',
          'post_keywords': '',
          'post_excerpt': '',
          'post_source': '',
          'post_content': '\n<p style="text-align: center;">　　《明日大亨（专服）》上线通知</p>\n<p style="text-align: center;"><br></p>\n<p><br></p>\n<p><br></p>\n<p><br></p>\n<p>《明日大亨（专服）》，于2022年11月03号，下午15:00:00开启‘’梦想1服’。</p>\n<p><br></p>\n<p><br></p>\n<p><br></p>\n<p><br></p>\n<p>《明日大亨（专服）》是一款现代商战题材的模拟经营手游，讲述一穷二白的打工人来到梦想岛，接受财富联盟资助，经过重重努力，坐拥豪车美女，逆袭大富豪的励志故事。游戏的开局，你将扮演身无分文却拥有超强商业思维的打工人，被财富联盟选中投资，从无到有经营店铺、创立公司，培养员工人才、经历各种商业考验，成为豪车美女随心选，登顶富豪榜的人生赢家！</p>\n<p><br></p>\n<p><br></p>\n<p><br></p>\n<p><br></p>\n<p>详细信息请登录app，搜索该款游戏查看。</p>\n',
          'post_content_filtered': null,
          'more': null,
          'agent_id': 1,
          'review_like': null,
          'review_hate': null,
          'title': '《明日大亨（专服）》上线通知',
          'excerpt': '',
          'game_id': 0,
          'pub_time': 1667550300,
          'type': '推广通知',
          'news_id': 6687,
          'game2': {
            'id': null,
            'name': null,
            'en_name': null,
            'en_abbr': null,
            'app_key': null,
            'tags': null,
            'category': null,
            'classify': null,
            'icon': null,
            'new_icon': null,
            'icon_share': null,
            'cp_payback_url': null,
            'cp_id': null,
            'parent_id': null,
            'package_name': null,
            'pay_switch': null,
            'logo_is_show': null,
            'float_is_show': null,
            'status': null,
            'is_delete': null,
            'delete_time': null,
            'is_online': null,
            'is_sdk': null,
            'is_bt': null,
            'is_auth': null,
            'list_order': null,
            'rise_order': null,
            'hot_order': null,
            'like_order': null,
            'fine_order': null,
            'publicity': null,
            'language': null,
            'description': null,
            'image': null,
            'run_time': null,
            'off_time': null,
            'create_time': null,
            'update_time': null,
            'promote_switch': null,
            'apple_id': null,
            'add_cp_time': null,
            'single_tag': null,
            'recycle_rate': null,
            'ext_info': null,
            'default_lang_code': null,
            'old_sign_key': null,
            'old_h5_game_id': null,
            'm3u8_url': null,
            'mp4_url': null,
            'mp4_type': null,
            'is_third': null,
            'selling_point': null,
            'gc_id': null,
            'real_name_tag': null,
            'real_name_bizid': null,
            'is_third_proper': null,
            'proper_game_id': null,
            'proper_agent_id': null,
            'is_box_proper': null,
            'add_status': null,
            'web_game_id': null
          },
          'img': '',
          'is_read': false
        },
        {
          'id': 6686,
          'app_id': 0,
          'parent_id': 0,
          'post_type': 6,
          'inform_type': 1,
          'cost_integral': '0.00',
          'post_format': 1,
          'user_id': 135845,
          'post_status': 2,
          'comment_status': 1,
          'is_top': 2,
          'recommended': 1,
          'post_hits': 286,
          'post_like': 0,
          'comment_count': 0,
          'create_time': 1667533733,
          'update_time': 1667533733,
          'start_time': 1667533620,
          'end_time': 1675440000,
          'published_time': 1667533620,
          'delete_time': 0,
          'url': '',
          'post_title': '《战地冲突（天雷无限刀）》上线通知',
          'post_author': '',
          'post_keywords': '',
          'post_excerpt': '',
          'post_source': '',
          'post_content': '\n<p style="text-align: center;">　　《战地冲突（天雷无限刀）》上线通知</p>\n<p><br></p>\n<p><br></p>\n<p><br></p>\n<p>《战地冲突（天雷无限刀）》，于2022年11月05号，上午08:00:00开启‘’天雷1服’。</p>\n<p><br></p>\n<p><br></p>\n<p><br></p>\n<p><br></p>\n<p>《战地冲突（天雷无限刀）》是一款高爆率的无限刀复古传奇手游。独创天雷系统打怪爆装燃炸全场，精美画风炫酷技能特效，超高爆率爆到爽。专属强力宝宝、结婚系统助您传奇之旅不再枯燥。尽享前所未有的收割快感，快来和兄弟一起问鼎沙城之巅！</p>\n<p><br></p>\n<p><br></p>\n<p><br></p>\n<p><br></p>\n<p>详细信息请登录app，搜索该款游戏查看。</p>\n',
          'post_content_filtered': null,
          'more': null,
          'agent_id': 1,
          'review_like': null,
          'review_hate': null,
          'title': '《战地冲突（天雷无限刀）》上线通知',
          'excerpt': '',
          'game_id': 0,
          'pub_time': 1667533620,
          'type': '推广通知',
          'news_id': 6686,
          'game2': {
            'id': null,
            'name': null,
            'en_name': null,
            'en_abbr': null,
            'app_key': null,
            'tags': null,
            'category': null,
            'classify': null,
            'icon': null,
            'new_icon': null,
            'icon_share': null,
            'cp_payback_url': null,
            'cp_id': null,
            'parent_id': null,
            'package_name': null,
            'pay_switch': null,
            'logo_is_show': null,
            'float_is_show': null,
            'status': null,
            'is_delete': null,
            'delete_time': null,
            'is_online': null,
            'is_sdk': null,
            'is_bt': null,
            'is_auth': null,
            'list_order': null,
            'rise_order': null,
            'hot_order': null,
            'like_order': null,
            'fine_order': null,
            'publicity': null,
            'language': null,
            'description': null,
            'image': null,
            'run_time': null,
            'off_time': null,
            'create_time': null,
            'update_time': null,
            'promote_switch': null,
            'apple_id': null,
            'add_cp_time': null,
            'single_tag': null,
            'recycle_rate': null,
            'ext_info': null,
            'default_lang_code': null,
            'old_sign_key': null,
            'old_h5_game_id': null,
            'm3u8_url': null,
            'mp4_url': null,
            'mp4_type': null,
            'is_third': null,
            'selling_point': null,
            'gc_id': null,
            'real_name_tag': null,
            'real_name_bizid': null,
            'is_third_proper': null,
            'proper_game_id': null,
            'proper_agent_id': null,
            'is_box_proper': null,
            'add_status': null,
            'web_game_id': null
          },
          'img': '',
          'is_read': false
        },
        {
          'id': 6682,
          'app_id': 0,
          'parent_id': 0,
          'post_type': 6,
          'inform_type': 1,
          'cost_integral': '0.00',
          'post_format': 1,
          'user_id': 135845,
          'post_status': 2,
          'comment_status': 1,
          'is_top': 2,
          'recommended': 1,
          'post_hits': 248,
          'post_like': 0,
          'comment_count': 0,
          'create_time': 1667530189,
          'update_time': 1667530189,
          'start_time': 1667530140,
          'end_time': 1675440000,
          'published_time': 1667530140,
          'delete_time': 0,
          'url': '',
          'post_title': '《仙侠传奇（超变无限刀）》停服公告',
          'post_author': '',
          'post_keywords': '',
          'post_excerpt': '',
          'post_source': '',
          'post_content': '\n<p>传奇无双移动版(送黄金战宠)关服公告</p>\n<p><br></p>\n<p>亲爱的各位玩家：</p>\n<p><br></p>\n<p>大家好!游戏《传奇无双移动版(送黄金战宠)》自上线以来，一直受到大家的支持，伴随着游戏一起成长的我们和您一样有着一种对游戏无法舍弃的感情。但如今，我们也只能放下自己的感情，希望得到您的理解并请您一如既往支持我们。由于运营策略变更，游戏将于2023年1月2日12点正式终止运营，关闭服务器，服务器关闭后玩家将无法登录游戏。对此我们表示深深的遗憾和诚挚的歉意!</p>\n<p><br></p>\n<p>现将有关停止运营的具体事项公布如下：</p>\n<p><br></p>\n<p>1、2022年11月2日，游戏新增注册功能将会关闭，老玩家可正常游戏;</p>\n<p><br></p>\n<p>2、2022年12月2日 , 游戏充值功能将会关闭，届时玩家将无法通过游戏进行充值，已充值的货币可以正常使用;</p>\n<p><br></p>\n<p>3、2023年1月2日12点，正式关闭服务器。</p>\n<p><br></p>\n<p>传奇无双移动版(送黄金战宠)运营团队</p>\n<p><br></p>\n<p>2022年11月2日</p>\n',
          'post_content_filtered': null,
          'more': null,
          'agent_id': 1,
          'review_like': null,
          'review_hate': null,
          'title': '《仙侠传奇（超变无限刀）》停服公告',
          'excerpt': '',
          'game_id': 0,
          'pub_time': 1667530140,
          'type': '推广通知',
          'news_id': 6682,
          'game2': {
            'id': null,
            'name': null,
            'en_name': null,
            'en_abbr': null,
            'app_key': null,
            'tags': null,
            'category': null,
            'classify': null,
            'icon': null,
            'new_icon': null,
            'icon_share': null,
            'cp_payback_url': null,
            'cp_id': null,
            'parent_id': null,
            'package_name': null,
            'pay_switch': null,
            'logo_is_show': null,
            'float_is_show': null,
            'status': null,
            'is_delete': null,
            'delete_time': null,
            'is_online': null,
            'is_sdk': null,
            'is_bt': null,
            'is_auth': null,
            'list_order': null,
            'rise_order': null,
            'hot_order': null,
            'like_order': null,
            'fine_order': null,
            'publicity': null,
            'language': null,
            'description': null,
            'image': null,
            'run_time': null,
            'off_time': null,
            'create_time': null,
            'update_time': null,
            'promote_switch': null,
            'apple_id': null,
            'add_cp_time': null,
            'single_tag': null,
            'recycle_rate': null,
            'ext_info': null,
            'default_lang_code': null,
            'old_sign_key': null,
            'old_h5_game_id': null,
            'm3u8_url': null,
            'mp4_url': null,
            'mp4_type': null,
            'is_third': null,
            'selling_point': null,
            'gc_id': null,
            'real_name_tag': null,
            'real_name_bizid': null,
            'is_third_proper': null,
            'proper_game_id': null,
            'proper_agent_id': null,
            'is_box_proper': null,
            'add_status': null,
            'web_game_id': null
          },
          'img': '',
          'is_read': false
        },
        {
          'id': 6681,
          'app_id': 0,
          'parent_id': 0,
          'post_type': 6,
          'inform_type': 1,
          'cost_integral': '0.00',
          'post_format': 1,
          'user_id': 135845,
          'post_status': 2,
          'comment_status': 1,
          'is_top': 2,
          'recommended': 1,
          'post_hits': 158,
          'post_like': 0,
          'comment_count': 0,
          'create_time': 1667528966,
          'update_time': 1667528966,
          'start_time': 1667528820,
          'end_time': 1675440000,
          'published_time': 1667528820,
          'delete_time': 0,
          'url': '',
          'post_title': '《猫三国（送千抽真充）》上线通知',
          'post_author': '',
          'post_keywords': '',
          'post_excerpt': '',
          'post_source': '',
          'post_content': '\n<p style="text-align: center;">　　《猫三国（送千抽真充）》上线通知</p>\n<p style="text-align: center;"><br></p>\n<p style="text-align: center;"><br></p>\n<p><br></p>\n<p>《猫三国（送千抽真充）》，于2022年11月04号，上午08:00:00开启‘’1区’。</p>\n<p><br></p>\n<p><br></p>\n<p><br></p>\n<p><br></p>\n<p>《猫三国（送千抽真充）》全新福利版本，创角即送VIP，尊享顶级VIP特权。再送328真充卡、1000武将连抽、自选金将、自选战马带来全新畅快开局体验。海量游戏福利，极速满级体验，经典三国题材的回合制角色扮演游戏，，颠覆传统卡牌手游模式，丰富多样的玩法，全自动托管小助手，精彩刺激的PK对决，轻松简单的武将培养，惊险刺激的实时国战，等你来战。</p>\n<p><br></p>\n<p><br></p>\n<p><br></p>\n<p><br></p>\n<p>详细信息请登录app，搜索该款游戏查看。</p>\n',
          'post_content_filtered': null,
          'more': null,
          'agent_id': 1,
          'review_like': null,
          'review_hate': null,
          'title': '《猫三国（送千抽真充）》上线通知',
          'excerpt': '',
          'game_id': 0,
          'pub_time': 1667528820,
          'type': '推广通知',
          'news_id': 6681,
          'game2': {
            'id': null,
            'name': null,
            'en_name': null,
            'en_abbr': null,
            'app_key': null,
            'tags': null,
            'category': null,
            'classify': null,
            'icon': null,
            'new_icon': null,
            'icon_share': null,
            'cp_payback_url': null,
            'cp_id': null,
            'parent_id': null,
            'package_name': null,
            'pay_switch': null,
            'logo_is_show': null,
            'float_is_show': null,
            'status': null,
            'is_delete': null,
            'delete_time': null,
            'is_online': null,
            'is_sdk': null,
            'is_bt': null,
            'is_auth': null,
            'list_order': null,
            'rise_order': null,
            'hot_order': null,
            'like_order': null,
            'fine_order': null,
            'publicity': null,
            'language': null,
            'description': null,
            'image': null,
            'run_time': null,
            'off_time': null,
            'create_time': null,
            'update_time': null,
            'promote_switch': null,
            'apple_id': null,
            'add_cp_time': null,
            'single_tag': null,
            'recycle_rate': null,
            'ext_info': null,
            'default_lang_code': null,
            'old_sign_key': null,
            'old_h5_game_id': null,
            'm3u8_url': null,
            'mp4_url': null,
            'mp4_type': null,
            'is_third': null,
            'selling_point': null,
            'gc_id': null,
            'real_name_tag': null,
            'real_name_bizid': null,
            'is_third_proper': null,
            'proper_game_id': null,
            'proper_agent_id': null,
            'is_box_proper': null,
            'add_status': null,
            'web_game_id': null
          },
          'img': '',
          'is_read': false
        },
        {
          'id': 6677,
          'app_id': 0,
          'parent_id': 0,
          'post_type': 6,
          'inform_type': 1,
          'cost_integral': '0.00',
          'post_format': 1,
          'user_id': 135845,
          'post_status': 2,
          'comment_status': 1,
          'is_top': 2,
          'recommended': 1,
          'post_hits': 189,
          'post_like': 0,
          'comment_count': 0,
          'create_time': 1667464950,
          'update_time': 1667464950,
          'start_time': 1667464860,
          'end_time': 1675353600,
          'published_time': 1667464860,
          'delete_time': 0,
          'url': '',
          'post_title': '《烈火骑士（暴击魂环觉醒）》上线通知',
          'post_author': '',
          'post_keywords': '',
          'post_excerpt': '',
          'post_source': '',
          'post_content': '\n<p style="text-align: center;">　　《烈火骑士（暴击魂环觉醒）》上线通知</p>\n<p style="text-align: center;"><br></p>\n<p><br></p>\n<p><br></p>\n<p>《烈火骑士（暴击魂环觉醒）》，于2022年11月06号，上午08:00:00开启‘’觉醒1服’。</p>\n<p><br></p>\n<p><br></p>\n<p><br></p>\n<p><br></p>\n<p>《烈火骑士（暴击魂环觉醒）》是一款以三国时代为背景的经典传奇游戏，拥有特色魂环系统，魂环加成逆天伤害！全新元素系统，全面提升各种属性，战力飙升爽翻天。游戏可自由PK，自由交易，也可以与其他玩家进行组队打BOSS和对战竞技，沙城捐献，激情攻沙，给您不—样的三国传奇体验！</p>\n<p><br></p>\n<p><br></p>\n<p><br></p>\n<p><br></p>\n<p>详细信息请登录app，搜索该款游戏查看。</p>\n',
          'post_content_filtered': null,
          'more': null,
          'agent_id': 1,
          'review_like': null,
          'review_hate': null,
          'title': '《烈火骑士（暴击魂环觉醒）》上线通知',
          'excerpt': '',
          'game_id': 0,
          'pub_time': 1667464860,
          'type': '推广通知',
          'news_id': 6677,
          'game2': {
            'id': null,
            'name': null,
            'en_name': null,
            'en_abbr': null,
            'app_key': null,
            'tags': null,
            'category': null,
            'classify': null,
            'icon': null,
            'new_icon': null,
            'icon_share': null,
            'cp_payback_url': null,
            'cp_id': null,
            'parent_id': null,
            'package_name': null,
            'pay_switch': null,
            'logo_is_show': null,
            'float_is_show': null,
            'status': null,
            'is_delete': null,
            'delete_time': null,
            'is_online': null,
            'is_sdk': null,
            'is_bt': null,
            'is_auth': null,
            'list_order': null,
            'rise_order': null,
            'hot_order': null,
            'like_order': null,
            'fine_order': null,
            'publicity': null,
            'language': null,
            'description': null,
            'image': null,
            'run_time': null,
            'off_time': null,
            'create_time': null,
            'update_time': null,
            'promote_switch': null,
            'apple_id': null,
            'add_cp_time': null,
            'single_tag': null,
            'recycle_rate': null,
            'ext_info': null,
            'default_lang_code': null,
            'old_sign_key': null,
            'old_h5_game_id': null,
            'm3u8_url': null,
            'mp4_url': null,
            'mp4_type': null,
            'is_third': null,
            'selling_point': null,
            'gc_id': null,
            'real_name_tag': null,
            'real_name_bizid': null,
            'is_third_proper': null,
            'proper_game_id': null,
            'proper_agent_id': null,
            'is_box_proper': null,
            'add_status': null,
            'web_game_id': null
          },
          'img': '',
          'is_read': false
        },
        {
          'id': 6673,
          'app_id': 0,
          'parent_id': 0,
          'post_type': 6,
          'inform_type': 1,
          'cost_integral': '0.00',
          'post_format': 1,
          'user_id': 135845,
          'post_status': 2,
          'comment_status': 1,
          'is_top': 2,
          'recommended': 1,
          'post_hits': 233,
          'post_like': 0,
          'comment_count': 0,
          'create_time': 1667457768,
          'update_time': 1667457768,
          'start_time': 1667457660,
          'end_time': 1675353600,
          'published_time': 1667457660,
          'delete_time': 0,
          'url': '',
          'post_title': '《轨迹幻想（送128充值）》上线通知',
          'post_author': '',
          'post_keywords': '',
          'post_excerpt': '',
          'post_source': '',
          'post_content': '\n<p style="text-align: center;">　　《轨迹幻想（送128充值）》上线通知</p>\n<p><br></p>\n<p><br></p>\n<p><br></p>\n<p>《轨迹幻想（送128充值）》，于2022年11月08号，上午09:00:00开启‘’球星1区’。</p>\n<p><br></p>\n<p><br></p>\n<p><br></p>\n<p><br></p>\n<p>《轨迹幻想（送128充值）》是一款足球题材的卡牌竞技手游，开局送128000钻石，30万金币，连续登录再送海量钻石和A+S级球员，还有更多活动白嫖到手软，沿着足球运动的轨迹一起奔跑，快来加入足球大世界吧！</p>\n<p><br></p>\n<p><br></p>\n<p><br></p>\n<p><br></p>\n<p>详细信息请登录app，搜索该款游戏查看。</p>\n',
          'post_content_filtered': null,
          'more': null,
          'agent_id': 1,
          'review_like': null,
          'review_hate': null,
          'title': '《轨迹幻想（送128充值）》上线通知',
          'excerpt': '',
          'game_id': 0,
          'pub_time': 1667457660,
          'type': '推广通知',
          'news_id': 6673,
          'game2': {
            'id': null,
            'name': null,
            'en_name': null,
            'en_abbr': null,
            'app_key': null,
            'tags': null,
            'category': null,
            'classify': null,
            'icon': null,
            'new_icon': null,
            'icon_share': null,
            'cp_payback_url': null,
            'cp_id': null,
            'parent_id': null,
            'package_name': null,
            'pay_switch': null,
            'logo_is_show': null,
            'float_is_show': null,
            'status': null,
            'is_delete': null,
            'delete_time': null,
            'is_online': null,
            'is_sdk': null,
            'is_bt': null,
            'is_auth': null,
            'list_order': null,
            'rise_order': null,
            'hot_order': null,
            'like_order': null,
            'fine_order': null,
            'publicity': null,
            'language': null,
            'description': null,
            'image': null,
            'run_time': null,
            'off_time': null,
            'create_time': null,
            'update_time': null,
            'promote_switch': null,
            'apple_id': null,
            'add_cp_time': null,
            'single_tag': null,
            'recycle_rate': null,
            'ext_info': null,
            'default_lang_code': null,
            'old_sign_key': null,
            'old_h5_game_id': null,
            'm3u8_url': null,
            'mp4_url': null,
            'mp4_type': null,
            'is_third': null,
            'selling_point': null,
            'gc_id': null,
            'real_name_tag': null,
            'real_name_bizid': null,
            'is_third_proper': null,
            'proper_game_id': null,
            'proper_agent_id': null,
            'is_box_proper': null,
            'add_status': null,
            'web_game_id': null
          },
          'img': '',
          'is_read': false
        },
        {
          'id': 6668,
          'app_id': 0,
          'parent_id': 0,
          'post_type': 6,
          'inform_type': 1,
          'cost_integral': '0.00',
          'post_format': 1,
          'user_id': 135845,
          'post_status': 2,
          'comment_status': 1,
          'is_top': 2,
          'recommended': 1,
          'post_hits': 218,
          'post_like': 0,
          'comment_count': 0,
          'create_time': 1667378472,
          'update_time': 1667378472,
          'start_time': 1667378340,
          'end_time': 1675267200,
          'published_time': 1667378340,
          'delete_time': 0,
          'url': '',
          'post_title': '《战国纪（高爆无限刀）》上线通知',
          'post_author': '',
          'post_keywords': '',
          'post_excerpt': '',
          'post_source': '',
          'post_content': '\n<p style="text-align: center;">　　《战国纪（高爆无限刀）》上线通知</p>\n<p style="text-align: center;"><br></p>\n<p style="text-align: center;"><br></p>\n<p><br></p>\n<p><br></p>\n<p>《战国纪（高爆无限刀）》，于2022年11月03号，上午08:00:00开启‘’战国1服’。</p>\n<p><br></p>\n<p><br></p>\n<p><br></p>\n<p>《战国纪（高爆无限刀）》这是一款精心打造的全新版本，超快刀速，超爽爆率，让玩家们有更极致的体验。刀刀切割，爽不停，上线就送50万货币和神器，还有各种福利送不停。游戏内有100多张地图任你刷，充值10倍返利，vip全返，各种材料和货币都能刷怪获取，赶快下载玩玩吧。</p>\n<p><br></p>\n<p><br></p>\n<p><br></p>\n<p>详细信息请登录app，搜索该款游戏查看。</p>\n',
          'post_content_filtered': null,
          'more': null,
          'agent_id': 1,
          'review_like': null,
          'review_hate': null,
          'title': '《战国纪（高爆无限刀）》上线通知',
          'excerpt': '',
          'game_id': 0,
          'pub_time': 1667378340,
          'type': '推广通知',
          'news_id': 6668,
          'game2': {
            'id': null,
            'name': null,
            'en_name': null,
            'en_abbr': null,
            'app_key': null,
            'tags': null,
            'category': null,
            'classify': null,
            'icon': null,
            'new_icon': null,
            'icon_share': null,
            'cp_payback_url': null,
            'cp_id': null,
            'parent_id': null,
            'package_name': null,
            'pay_switch': null,
            'logo_is_show': null,
            'float_is_show': null,
            'status': null,
            'is_delete': null,
            'delete_time': null,
            'is_online': null,
            'is_sdk': null,
            'is_bt': null,
            'is_auth': null,
            'list_order': null,
            'rise_order': null,
            'hot_order': null,
            'like_order': null,
            'fine_order': null,
            'publicity': null,
            'language': null,
            'description': null,
            'image': null,
            'run_time': null,
            'off_time': null,
            'create_time': null,
            'update_time': null,
            'promote_switch': null,
            'apple_id': null,
            'add_cp_time': null,
            'single_tag': null,
            'recycle_rate': null,
            'ext_info': null,
            'default_lang_code': null,
            'old_sign_key': null,
            'old_h5_game_id': null,
            'm3u8_url': null,
            'mp4_url': null,
            'mp4_type': null,
            'is_third': null,
            'selling_point': null,
            'gc_id': null,
            'real_name_tag': null,
            'real_name_bizid': null,
            'is_third_proper': null,
            'proper_game_id': null,
            'proper_agent_id': null,
            'is_box_proper': null,
            'add_status': null,
            'web_game_id': null
          },
          'img': '',
          'is_read': false
        },
        {
          'id': 6663,
          'app_id': 0,
          'parent_id': 0,
          'post_type': 6,
          'inform_type': 1,
          'cost_integral': '0.00',
          'post_format': 1,
          'user_id': 135845,
          'post_status': 2,
          'comment_status': 1,
          'is_top': 2,
          'recommended': 1,
          'post_hits': 231,
          'post_like': 0,
          'comment_count': 0,
          'create_time': 1667374718,
          'update_time': 1667374718,
          'start_time': 1667374620,
          'end_time': 1675267200,
          'published_time': 1667374620,
          'delete_time': 0,
          'url': '',
          'post_title': '《明日大亨》上线通知',
          'post_author': '',
          'post_keywords': '',
          'post_excerpt': '',
          'post_source': '',
          'post_content': '\n<p style="text-align: center;">　　《明日大亨》上线通知</p>\n<p style="text-align: center;"><br></p>\n<p style="text-align: center;"><br></p>\n<p style="text-align: center;"><br></p>\n<p style="text-align: center;"><br></p>\n<p>《明日大亨》，于2022年11月02号，上午开启‘’动态开区’。</p>\n<p><br></p>\n<p><br></p>\n<p><br></p>\n<p><br></p>\n<p>《明日大亨》是一款现代商战题材的模拟经营手游，讲述一穷二白的打工人来到梦想岛，接受财富联盟资助，经过重重努力，坐拥豪车美女，逆袭大富豪的励志故事。游戏的开局，你将扮演身无分文却拥有超强商业思维的打工人，被财富联盟选中投资，从无到有经营店铺、创立公司，培养员工人才、经历各种商业考验，成为豪车美女随心选，登顶富豪榜的人生赢家！</p>\n<p><br></p>\n<p><br></p>\n<p><br></p>\n<p><br></p>\n<p>详细信息请登录app，搜索该款游戏查看。</p>\n',
          'post_content_filtered': null,
          'more': null,
          'agent_id': 1,
          'review_like': null,
          'review_hate': null,
          'title': '《明日大亨》上线通知',
          'excerpt': '',
          'game_id': 0,
          'pub_time': 1667374620,
          'type': '推广通知',
          'news_id': 6663,
          'game2': {
            'id': null,
            'name': null,
            'en_name': null,
            'en_abbr': null,
            'app_key': null,
            'tags': null,
            'category': null,
            'classify': null,
            'icon': null,
            'new_icon': null,
            'icon_share': null,
            'cp_payback_url': null,
            'cp_id': null,
            'parent_id': null,
            'package_name': null,
            'pay_switch': null,
            'logo_is_show': null,
            'float_is_show': null,
            'status': null,
            'is_delete': null,
            'delete_time': null,
            'is_online': null,
            'is_sdk': null,
            'is_bt': null,
            'is_auth': null,
            'list_order': null,
            'rise_order': null,
            'hot_order': null,
            'like_order': null,
            'fine_order': null,
            'publicity': null,
            'language': null,
            'description': null,
            'image': null,
            'run_time': null,
            'off_time': null,
            'create_time': null,
            'update_time': null,
            'promote_switch': null,
            'apple_id': null,
            'add_cp_time': null,
            'single_tag': null,
            'recycle_rate': null,
            'ext_info': null,
            'default_lang_code': null,
            'old_sign_key': null,
            'old_h5_game_id': null,
            'm3u8_url': null,
            'mp4_url': null,
            'mp4_type': null,
            'is_third': null,
            'selling_point': null,
            'gc_id': null,
            'real_name_tag': null,
            'real_name_bizid': null,
            'is_third_proper': null,
            'proper_game_id': null,
            'proper_agent_id': null,
            'is_box_proper': null,
            'add_status': null,
            'web_game_id': null
          },
          'img': '',
          'is_read': false
        },
        {
          'id': 6661,
          'app_id': 0,
          'parent_id': 0,
          'post_type': 6,
          'inform_type': 1,
          'cost_integral': '0.00',
          'post_format': 1,
          'user_id': 1,
          'post_status': 2,
          'comment_status': 1,
          'is_top': 2,
          'recommended': 1,
          'post_hits': 274,
          'post_like': 0,
          'comment_count': 0,
          'create_time': 1667301537,
          'update_time': 1667301537,
          'start_time': 1667301480,
          'end_time': 1675180800,
          'published_time': 1667301480,
          'delete_time': 0,
          'url': '',
          'post_title': '《御龙弑天》通知',
          'post_author': '',
          'post_keywords': '',
          'post_excerpt': '',
          'post_source': '',
          'post_content': '\n<p style="text-align: center;">　　《御龙弑天》通知</p>\n<p style="text-align: center;"><br></p>\n<p><span style="color: rgb(0, 0, 0);">【4000yx年底主推产品 预约渠道50+】</span></p>\n<p><span style="color: rgb(0, 0, 0);">【御龙弑天】新大区【全新返利表日结产品</span></p>\n<p><span style="color: rgb(0, 0, 0);">11月3号3点首区上线 专属客服返利模式资料 独家产品，35倍返利进游送10000全新职业 </span></p>\n<p><span style="color: rgb(0, 0, 0);">新增首充一元满V，各类极品武器绝版跑车</span></p>\n<p><span style="color: rgb(0, 0, 0);">绝版坐骑、绝版神龙10亿金币，享用不尽，</span></p>\n<p><span style="color: rgb(0, 0, 0);">每日有专人监控游戏生态，防拉人，防折扣</span></p>\n<p><span style="color: rgb(0, 0, 0);">直播授权短视频授权，成熟御龙直播体系，可供学习复制，</span></p>\n<p><span style="color: rgb(0, 0, 0);">抖音买量 主播推广产品，高扶持返利高配合力度。</span></p>\n<p><span style="color: rgb(0, 0, 0);">​年底吃肉产品抓紧时间上车！！</span></p>\n',
          'post_content_filtered': null,
          'more': null,
          'agent_id': 1,
          'review_like': null,
          'review_hate': null,
          'title': '《御龙弑天》通知',
          'excerpt': '',
          'game_id': 0,
          'pub_time': 1667301480,
          'type': '推广通知',
          'news_id': 6661,
          'game2': {
            'id': null,
            'name': null,
            'en_name': null,
            'en_abbr': null,
            'app_key': null,
            'tags': null,
            'category': null,
            'classify': null,
            'icon': null,
            'new_icon': null,
            'icon_share': null,
            'cp_payback_url': null,
            'cp_id': null,
            'parent_id': null,
            'package_name': null,
            'pay_switch': null,
            'logo_is_show': null,
            'float_is_show': null,
            'status': null,
            'is_delete': null,
            'delete_time': null,
            'is_online': null,
            'is_sdk': null,
            'is_bt': null,
            'is_auth': null,
            'list_order': null,
            'rise_order': null,
            'hot_order': null,
            'like_order': null,
            'fine_order': null,
            'publicity': null,
            'language': null,
            'description': null,
            'image': null,
            'run_time': null,
            'off_time': null,
            'create_time': null,
            'update_time': null,
            'promote_switch': null,
            'apple_id': null,
            'add_cp_time': null,
            'single_tag': null,
            'recycle_rate': null,
            'ext_info': null,
            'default_lang_code': null,
            'old_sign_key': null,
            'old_h5_game_id': null,
            'm3u8_url': null,
            'mp4_url': null,
            'mp4_type': null,
            'is_third': null,
            'selling_point': null,
            'gc_id': null,
            'real_name_tag': null,
            'real_name_bizid': null,
            'is_third_proper': null,
            'proper_game_id': null,
            'proper_agent_id': null,
            'is_box_proper': null,
            'add_status': null,
            'web_game_id': null
          },
          'img': '',
          'is_read': true
        },
        {
          'id': 6658,
          'app_id': 0,
          'parent_id': 0,
          'post_type': 6,
          'inform_type': 1,
          'cost_integral': '0.00',
          'post_format': 1,
          'user_id': 135845,
          'post_status': 2,
          'comment_status': 1,
          'is_top': 2,
          'recommended': 1,
          'post_hits': 213,
          'post_like': 0,
          'comment_count': 0,
          'create_time': 1667289860,
          'update_time': 1667289860,
          'start_time': 1667289780,
          'end_time': 1675180800,
          'published_time': 1667289780,
          'delete_time': 0,
          'url': '',
          'post_title': '《青云诀2》上线通知',
          'post_author': '',
          'post_keywords': '',
          'post_excerpt': '',
          'post_source': '',
          'post_content': '\n<p style="text-align: center;">　　《青云诀2》上线通知</p>\n<p style="text-align: center;"><br></p>\n<p style="text-align: center;"><br></p>\n<p style="text-align: center;"><br></p>\n<p style="text-align: center;"><br></p>\n<p>《青云诀2》，于2022年11月01号，上午开启‘’动态开区’。</p>\n<p><br></p>\n<p><br></p>\n<p><br></p>\n<p><br></p>\n<p>《青云诀2》是一款全新剧情仙侠题材3DMMORPG游戏！ [1]  传承青云系列核心玩法，如青云之巅，仙魔争霸，巅峰对决等玩法，以天神坐骑副本、技能PK、拍卖系统等为主要玩点。</p>\n<p><br></p>\n<p><br></p>\n<p><br></p>\n<p><br></p>\n<p>详细信息请登录app，搜索该款游戏查看。</p>\n',
          'post_content_filtered': null,
          'more': null,
          'agent_id': 1,
          'review_like': null,
          'review_hate': null,
          'title': '《青云诀2》上线通知',
          'excerpt': '',
          'game_id': 0,
          'pub_time': 1667289780,
          'type': '推广通知',
          'news_id': 6658,
          'game2': {
            'id': null,
            'name': null,
            'en_name': null,
            'en_abbr': null,
            'app_key': null,
            'tags': null,
            'category': null,
            'classify': null,
            'icon': null,
            'new_icon': null,
            'icon_share': null,
            'cp_payback_url': null,
            'cp_id': null,
            'parent_id': null,
            'package_name': null,
            'pay_switch': null,
            'logo_is_show': null,
            'float_is_show': null,
            'status': null,
            'is_delete': null,
            'delete_time': null,
            'is_online': null,
            'is_sdk': null,
            'is_bt': null,
            'is_auth': null,
            'list_order': null,
            'rise_order': null,
            'hot_order': null,
            'like_order': null,
            'fine_order': null,
            'publicity': null,
            'language': null,
            'description': null,
            'image': null,
            'run_time': null,
            'off_time': null,
            'create_time': null,
            'update_time': null,
            'promote_switch': null,
            'apple_id': null,
            'add_cp_time': null,
            'single_tag': null,
            'recycle_rate': null,
            'ext_info': null,
            'default_lang_code': null,
            'old_sign_key': null,
            'old_h5_game_id': null,
            'm3u8_url': null,
            'mp4_url': null,
            'mp4_type': null,
            'is_third': null,
            'selling_point': null,
            'gc_id': null,
            'real_name_tag': null,
            'real_name_bizid': null,
            'is_third_proper': null,
            'proper_game_id': null,
            'proper_agent_id': null,
            'is_box_proper': null,
            'add_status': null,
            'web_game_id': null
          },
          'img': '',
          'is_read': true
        },
        {
          'id': 6656,
          'app_id': 0,
          'parent_id': 0,
          'post_type': 6,
          'inform_type': 1,
          'cost_integral': '0.00',
          'post_format': 1,
          'user_id': 1,
          'post_status': 2,
          'comment_status': 1,
          'is_top': 2,
          'recommended': 1,
          'post_hits': 250,
          'post_like': 0,
          'comment_count': 0,
          'create_time': 1667287027,
          'update_time': 1667287027,
          'start_time': 1667286780,
          'end_time': 1675180800,
          'published_time': 1667286780,
          'delete_time': 0,
          'url': '',
          'post_title': '《御龙弑天》维护开区公告',
          'post_author': '',
          'post_keywords': '',
          'post_excerpt': '',
          'post_source': '',
          'post_content': '\n<p>                                                                                                      《御龙弑天》维护开区公告</p>\n<p><br></p>\n<p>2022年11月1日因更新返利表，故此暂停开区一天，返利表更新完成后会同步到御龙在线返利文档以及pro后台资源申请中，已更新完成望周知！！！</p>\n<p><br></p>\n<p><span style="color: rgb(0, 0, 0);">[御龙弑天]侠士们，为了更好的游戏体验，我们将于11月3日15:00开启新大区【虎踞龙盘】</span></p>\n<p><span style="color: rgb(0, 0, 0);">[服务器名]虎踞1区</span></p>\n<p><span style="color: rgb(0, 0, 0);">[开服时间] 11月3日15:00</span></p>\n<p><span style="color: rgb(0, 0, 0);">《御龙弑天》虎踞1区将于11月3日15:00正式开启</span></p>\n<p><span style="color: rgb(0, 0, 0);">为此我们准备了更多福利</span></p>\n<p><span style="color: rgb(0, 0, 0);">1，每日福利调整为5000【只限虎踞龙盘首服】</span></p>\n<p><span style="color: rgb(0, 0, 0);">2，新大区首服预约礼包 【只限虎踞龙盘首服】</span></p>\n<p><br></p>\n',
          'post_content_filtered': null,
          'more': null,
          'agent_id': 1,
          'review_like': null,
          'review_hate': null,
          'title': '《御龙弑天》维护开区公告',
          'excerpt': '',
          'game_id': 0,
          'pub_time': 1667286780,
          'type': '推广通知',
          'news_id': 6656,
          'game2': {
            'id': null,
            'name': null,
            'en_name': null,
            'en_abbr': null,
            'app_key': null,
            'tags': null,
            'category': null,
            'classify': null,
            'icon': null,
            'new_icon': null,
            'icon_share': null,
            'cp_payback_url': null,
            'cp_id': null,
            'parent_id': null,
            'package_name': null,
            'pay_switch': null,
            'logo_is_show': null,
            'float_is_show': null,
            'status': null,
            'is_delete': null,
            'delete_time': null,
            'is_online': null,
            'is_sdk': null,
            'is_bt': null,
            'is_auth': null,
            'list_order': null,
            'rise_order': null,
            'hot_order': null,
            'like_order': null,
            'fine_order': null,
            'publicity': null,
            'language': null,
            'description': null,
            'image': null,
            'run_time': null,
            'off_time': null,
            'create_time': null,
            'update_time': null,
            'promote_switch': null,
            'apple_id': null,
            'add_cp_time': null,
            'single_tag': null,
            'recycle_rate': null,
            'ext_info': null,
            'default_lang_code': null,
            'old_sign_key': null,
            'old_h5_game_id': null,
            'm3u8_url': null,
            'mp4_url': null,
            'mp4_type': null,
            'is_third': null,
            'selling_point': null,
            'gc_id': null,
            'real_name_tag': null,
            'real_name_bizid': null,
            'is_third_proper': null,
            'proper_game_id': null,
            'proper_agent_id': null,
            'is_box_proper': null,
            'add_status': null,
            'web_game_id': null
          },
          'img': '',
          'is_read': false
        },
        {
          'id': 6655,
          'app_id': 0,
          'parent_id': 0,
          'post_type': 6,
          'inform_type': 1,
          'cost_integral': '0.00',
          'post_format': 1,
          'user_id': 135845,
          'post_status': 2,
          'comment_status': 1,
          'is_top': 2,
          'recommended': 1,
          'post_hits': 209,
          'post_like': 0,
          'comment_count': 0,
          'create_time': 1667274607,
          'update_time': 1667274607,
          'start_time': 1667274480,
          'end_time': 1675180800,
          'published_time': 1667274480,
          'delete_time': 0,
          'url': '',
          'post_title': '《航海霸业》上线通知',
          'post_author': '',
          'post_keywords': '',
          'post_excerpt': '',
          'post_source': '',
          'post_content': '\n<p style="text-align: center;">　　《航海霸业》上线通知</p>\n<p style="text-align: center;"><br></p>\n<p style="text-align: center;"><br></p>\n<p style="text-align: center;"><br></p>\n<p style="text-align: center;"><br></p>\n<p>《航海霸业》，于2022年11月28号，开启“动态开区”</p>\n<p><br></p>\n<p><br></p>\n<p>《航海霸业》游戏中的货物都体现了对16世纪的欧洲的忠实还原，在地中海和北海，波罗的海沿岸，有许多海运和贸易发达的港口，这些港口出产独具地域特色的货物，您可以将一些商品从原产地低价买入，然后运到大海的另一面卖出，从中体验到世界各地的特产与风土人情。</p>\n<p><br></p>\n<p>详细信息请登录app，搜索该款游戏查看。</p>\n',
          'post_content_filtered': null,
          'more': null,
          'agent_id': 1,
          'review_like': null,
          'review_hate': null,
          'title': '《航海霸业》上线通知',
          'excerpt': '',
          'game_id': 0,
          'pub_time': 1667274480,
          'type': '推广通知',
          'news_id': 6655,
          'game2': {
            'id': null,
            'name': null,
            'en_name': null,
            'en_abbr': null,
            'app_key': null,
            'tags': null,
            'category': null,
            'classify': null,
            'icon': null,
            'new_icon': null,
            'icon_share': null,
            'cp_payback_url': null,
            'cp_id': null,
            'parent_id': null,
            'package_name': null,
            'pay_switch': null,
            'logo_is_show': null,
            'float_is_show': null,
            'status': null,
            'is_delete': null,
            'delete_time': null,
            'is_online': null,
            'is_sdk': null,
            'is_bt': null,
            'is_auth': null,
            'list_order': null,
            'rise_order': null,
            'hot_order': null,
            'like_order': null,
            'fine_order': null,
            'publicity': null,
            'language': null,
            'description': null,
            'image': null,
            'run_time': null,
            'off_time': null,
            'create_time': null,
            'update_time': null,
            'promote_switch': null,
            'apple_id': null,
            'add_cp_time': null,
            'single_tag': null,
            'recycle_rate': null,
            'ext_info': null,
            'default_lang_code': null,
            'old_sign_key': null,
            'old_h5_game_id': null,
            'm3u8_url': null,
            'mp4_url': null,
            'mp4_type': null,
            'is_third': null,
            'selling_point': null,
            'gc_id': null,
            'real_name_tag': null,
            'real_name_bizid': null,
            'is_third_proper': null,
            'proper_game_id': null,
            'proper_agent_id': null,
            'is_box_proper': null,
            'add_status': null,
            'web_game_id': null
          },
          'img': '',
          'is_read': false
        },
        {
          'id': 6652,
          'app_id': 0,
          'parent_id': 0,
          'post_type': 6,
          'inform_type': 1,
          'cost_integral': '0.00',
          'post_format': 1,
          'user_id': 135845,
          'post_status': 2,
          'comment_status': 1,
          'is_top': 2,
          'recommended': 1,
          'post_hits': 251,
          'post_like': 0,
          'comment_count': 0,
          'create_time': 1667268224,
          'update_time': 1667268224,
          'start_time': 1667268120,
          'end_time': 1675180800,
          'published_time': 1667268120,
          'delete_time': 0,
          'url': '',
          'post_title': '《暗黑前传（魂环满攻速）》上线通知',
          'post_author': '',
          'post_keywords': '',
          'post_excerpt': '',
          'post_source': '',
          'post_content': '\n<p style="text-align: center;">　　《暗黑前传（魂环满攻速）》上线通知</p>\n<p style="text-align: center;"><br></p>\n<p style="text-align: center;"><br></p>\n<p style="text-align: center;"><br></p>\n<p>《暗黑前传（魂环满攻速）》，于2022年11月01号，上午08:00:00开启‘’暗黑1区’。</p>\n<p><br></p>\n<p><br></p>\n<p><br></p>\n<p>《暗黑前传（魂环满攻速）》是一款融合武侠和传奇元素的创新手游，游戏继承了传奇的核心玩法，登陆送魂环，登录送全屏吸怪技能，免费升满攻速，无限刀、刀刀切割爽快杀怪，无VIP散人福利服，BOSS爆充值红包，还有六脉神剑、易筋经、洗髓经等特色玩法，称霸江湖，等你来战！</p>\n<p><br></p>\n<p><br></p>\n<p><br></p>\n<p>详细信息请登录app，搜索该款游戏查看。</p>\n',
          'post_content_filtered': null,
          'more': null,
          'agent_id': 1,
          'review_like': null,
          'review_hate': null,
          'title': '《暗黑前传（魂环满攻速）》上线通知',
          'excerpt': '',
          'game_id': 0,
          'pub_time': 1667268120,
          'type': '推广通知',
          'news_id': 6652,
          'game2': {
            'id': null,
            'name': null,
            'en_name': null,
            'en_abbr': null,
            'app_key': null,
            'tags': null,
            'category': null,
            'classify': null,
            'icon': null,
            'new_icon': null,
            'icon_share': null,
            'cp_payback_url': null,
            'cp_id': null,
            'parent_id': null,
            'package_name': null,
            'pay_switch': null,
            'logo_is_show': null,
            'float_is_show': null,
            'status': null,
            'is_delete': null,
            'delete_time': null,
            'is_online': null,
            'is_sdk': null,
            'is_bt': null,
            'is_auth': null,
            'list_order': null,
            'rise_order': null,
            'hot_order': null,
            'like_order': null,
            'fine_order': null,
            'publicity': null,
            'language': null,
            'description': null,
            'image': null,
            'run_time': null,
            'off_time': null,
            'create_time': null,
            'update_time': null,
            'promote_switch': null,
            'apple_id': null,
            'add_cp_time': null,
            'single_tag': null,
            'recycle_rate': null,
            'ext_info': null,
            'default_lang_code': null,
            'old_sign_key': null,
            'old_h5_game_id': null,
            'm3u8_url': null,
            'mp4_url': null,
            'mp4_type': null,
            'is_third': null,
            'selling_point': null,
            'gc_id': null,
            'real_name_tag': null,
            'real_name_bizid': null,
            'is_third_proper': null,
            'proper_game_id': null,
            'proper_agent_id': null,
            'is_box_proper': null,
            'add_status': null,
            'web_game_id': null
          },
          'img': '',
          'is_read': false
        }
      ]
    }
  },
  computed: {
    ...mapGetters([
      'name',
      'avatar',
      'roles'
    ])
  },
  created() {
    this.total = this.notices.length
    this.total = 1770
    // 临时数组对象C
    for (let i = 0; i < 8; i++) {
      // 为arrayA[i]添加名称为name的属性字段，值等于arrayC[arrayA[i].id]
      this.noticeList[i] = this.notices[i]
    }
  },
  methods: {
    getList() {
      if (this.listQuery.page > 2) {
        return
      }
      var tmpPage = this.listQuery.page > 2 ? 2 : this.listQuery.page
      var tmpLength = tmpPage * 8
      var tmpIndex = (tmpPage - 1) * 8
      var tmnpArr = []
      for (let i = tmpIndex; i < tmpLength; i++) {
      // 为arrayA[i]添加名称为name的属性字段，值等于arrayC[arrayA[i].id]
        tmnpArr[i - tmpIndex] = this.notices[i]
      }
      this.noticeList = tmnpArr
    },
    getUnRead() {
      var tmnpArr = []
      for (let i = (this.notices.length - 1); i >= 0; i--) {
      // 为arrayA[i]添加名称为name的属性字段，值等于arrayC[arrayA[i].id]
        var tmpObj = this.notices[i]
        if (!tmpObj.is_read) {
          // tmnpArr[i - tmpIndex] = this.notices[i]
          tmnpArr.push(this.notices[i])
        }
      }
      console.log(tmnpArr)
      this.noticeList = tmnpArr
    },
    changeTab(item) {
      console.log(item)
      // eslint-disable-next-line eqeqeq
      if (item == '公告') {
        this.indexSelect = 0
        this.total = 1770
        this.getList()
      } else {
        this.indexSelect = 1
        this.total = 0
        this.getUnRead()
      }
    }
  }
}
</script>

<style lang="scss" >
.box-card-component{
  .el-card__header {
    padding: 0px!important;
  }
}
</style>
<style lang="scss" scoped>
.pagination-holder{
  display: flex;
  flex-direction: row;
  justify-content: center;
  /* align-items: center; */
  justify-items: center;
  /* width: 100%; */
}
.pagination-total{
  text-align: right;
  width: 75px;
  line-height: 75px;
  font-size: 13px;
  // height: 28px;
  // line-height: 28px;
}
.box-card-component {
  font-family: PingFang SC,Helvetica Neue,Helvetica,microsoft yahei,arial,STHeiTi,sans-serif;
  .btn-box{
    display: flex;
    flex-direction: row;
    align-items: center;
    justify-content: start;
    margin-top: 20px;
    margin-bottom: 8px;
  }
  .btn-panel-select{
    color: white;
    background-color: #52a3c8;
    margin-right: 15px;
    padding: 8px 12px;
    border-radius: 2px;
  }
  .btn-panel-normal{
    color: #000;
    background-color:#f2f2f2;
    margin-right: 15px;
    padding: 8px 12px;
    border-radius: 2px;
  }
  .box-card-header {
    padding-top: 15px;
    // padding-left: 15px;
    padding-bottom: 12px;
    border-bottom: 1px dashed #ccc;
    color: rgb(88, 88, 88);
    font-size: 20px;
    font-family: PingFang SC,Helvetica Neue,Helvetica,microsoft yahei,arial,STHeiTi,sans-serif;
  }
  .card-right{
    font-size: 15px;
    position: relative;
    display: flex;
    flex-direction: row;
    align-items: center;
    justify-content:space-between;
    border-bottom: 0.5px solid #dcd8d8;
    height: 56px;
    padding: 0px 10px;
  }

  .list-left-box{
    display: flex;
    align-items: center;
  }

  .list-left-box::before{
    content: "";
    position: absolute;
    left: 0;
    top: 23px;
    width: 6px;
    height: 6px;
    border-radius: 50%;
    background-color: #dedede;
  }

  .list-left-title{
    color: #3e9eff;
    font-size: 13px;
    line-height: 26px;
  }

  .list-left-content{
    color: #696969;
    white-space: nowrap;
    font-size: 13px;
    line-height: 26px;
  }

  .list-left-time{
    color: #999;
    font-size: 12px;
    line-height: 26px;
  }

  .card-panel-icon{
    color: #333;
    font-size: 15px;
  }

  .btn-copy{
    font-size: 12px;
    padding: 6px 8px;
  }

  .panThumb {
    z-index: 100;
    height: 70px!important;
    width: 70px!important;
    position: absolute!important;
    top: -45px;
    left: 0px;
    border: 5px solid #ffffff;
    background-color: #fff;
    margin: auto;
    box-shadow: none!important;
    ::v-deep .pan-info {
      box-shadow: none!important;
    }
  }
  .progress-item {
    margin-bottom: 10px;
    font-size: 14px;
  }
  @media only screen and (max-width: 1510px){
    .mallki-text{
      display: none;
    }
  }
}
</style>
